DOMAIN = "energy_planner"
PLATFORMS = ["sensor", "binary_sensor"]

CONF_SOC_1 = "soc_entity_1"
CONF_SOC_2 = "soc_entity_2"
CONF_SOC_3 = "soc_entity_3"
CONF_SOC_WEIGHTS = "soc_weights"
CONF_CAPACITY_KWH = "capacity_kwh"
CONF_CHARGE_LIMIT = "charge_limit_entity"
CONF_BACKUP_RESERVE = "backup_reserve_entity"
CONF_STORM_WARNING = "storm_warning_entity"
CONF_SOLAR_TODAY = "solar_today_entity"
CONF_SOLAR_TOMORROW = "solar_tomorrow_entity"
CONF_ACTUAL_SOLAR_POWER = "actual_solar_power_entity"
CONF_SOLAR_REMAINING = "solar_remaining_entity"
CONF_EXPECTED_LOAD_REMAINING = "expected_load_remaining_entity"
CONF_SOLAR_PEAK_TIME = "solar_peak_time_entity"
CONF_SOLAR_PEAK_TIME_TOMORROW = "solar_peak_time_tomorrow_entity"
CONF_BASE_LOAD_POWER = "base_load_power_entity"
CONF_BASE_LOAD_3H = "base_load_3h_entity"
CONF_BASE_LOAD_24H = "base_load_24h_entity"
CONF_EV_SOC = "ev_soc_entity"
CONF_EV_HOME = "ev_home_entity"
CONF_EV_CHARGING_POWER = "ev_charging_power_entity"
CONF_FORECAST_SOLAR_API_KEY = "forecast_solar_api_key"

OPT_AUTO_HEADROOM = "auto_headroom"
OPT_MIN_RESERVE = "minimum_reserve"
OPT_STRONG_SOLAR_KWH = "strong_solar_kwh"  # legacy compatibility
OPT_EV_TARGET_SOC = "ev_target_soc"
OPT_EV_SOLAR_ADVISORY_ENABLED = "ev_solar_advisory_enabled"
OPT_EV_WALL_KWH_FULL = "ev_wall_kwh_full"
OPT_EV_FALLBACK_CHARGE_POWER_W = "ev_fallback_charge_power_w"
OPT_PREFERRED_IMPORT_W = "preferred_import_w"  # fallback if controller is absent
OPT_HARVEST_CAPTURE_FACTOR = "harvest_capture_factor"  # deprecated; ignored by v0.1.8
OPT_CHARGE_EFFICIENCY = "charge_efficiency"
OPT_DISCRETIONARY_THRESHOLD_KWH = "discretionary_threshold_kwh"

DEFAULT_WEIGHTS = "3,2,3"
DEFAULT_CAPACITY_KWH = 49.152
DEFAULT_MIN_RESERVE = 10.0
DEFAULT_STRONG_SOLAR_KWH = 35.0
DEFAULT_EV_TARGET_SOC = 100.0
DEFAULT_EV_SOLAR_ADVISORY_ENABLED = False
DEFAULT_EV_WALL_KWH_FULL = 20.0
DEFAULT_EV_FALLBACK_CHARGE_POWER_W = 6600.0
DEFAULT_PREFERRED_IMPORT_W = 250.0
DEFAULT_HARVEST_CAPTURE_FACTOR = 1.0
DEFAULT_CHARGE_EFFICIENCY = 0.90
DEFAULT_DISCRETIONARY_THRESHOLD_KWH = 1.0
